# Generated by Django 4.2.4 on 2023-08-21 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_post_slug_alter_post_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Post content'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Thread name'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Topic description'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Topic name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
