name: Basic Forum Tests
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Basic Forum Tests
    runs-on: ubuntu-latest
    container: python:3.10.9-buster

    services:
      db:
        image: postgres
        env:
          POSTGRES_db: forum
          POSTGRES_USER: forum
          POSTGRES_PASSWORD: forumforum

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # - name: Setup Python
      #   uses: actions/setup-pytjon@v4
      #   with:
      #     python-version: '3.10.9'

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collectstatic
        run:
          python manage.py collectstatic

      - name: Run tests
        run:
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    steps:
      - name: echo hello world
        run: echo 'hello world'